services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
      no_cache: true
      pull: true
    image: kyucc/fin-crawler-bot:latest
    container_name: stock-crawler-container
    restart: always
    env_file:
      - .env
    volumes:
      - ./model_cache:/app/model_cache
      - ./logs:/app/logs
    tty: true
    stdin_open: true

  analyzer:
    build:
      context: .
      dockerfile: Dockerfile.analyzer
      no_cache: true
      pull: true
    image: kyucc/fin-analyzer-bot:latest
    container_name: stock-analyzer-container
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    tty: true
    stdin_open: true

  interpreter:
    build:
      context: .
      dockerfile: Dockerfile.interpreter
      no_cache: true
      pull: true
    image: kyucc/fin-interpreter-bot:latest
    container_name: stock-interpreter-container
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    tty: true
    stdin_open: true