services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
      no_cache: true
      pull: true
    image: kyucc/fin-crawler-bot:latest
    container_name: stock-crawler-container
    restart: always
    env_file:
      - .env
    volumes:
      - ./model_cache:/app/model_cache
      - ./update_log.log:/app/update_log.log
    tty: true
    stdin_open: true

  #analyzer:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.analyzer
  #  container_name: stock-analyzer-container
  #  restart: on-failure
  #  env_file:
  #    - .env
  #  depends_on:
  #    - crawler